---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-7
  - name: debian-8
  - name: centos-6
  - name: centos-7
  - name: fedora-21
  - name: fedora-22

suites:
  - name: default
    run_list:
      - recipe[chef-client-hardening]
